apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/3scale-operator-product-build?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudge-files: "catalog/(.*)/catalog.json, catalog/(.*)/catalog-template.json"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # when adding filter for directory use "directory/***".pathChanged()
    # when adding filter for git submodule use "submodule".pathChanged()
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/threescale-operator-bundle-pull-request.yaml".pathChanged() ||
      ".tekton/threescale-operator-bundle-push.yaml".pathChanged() ||
      "Containerfile.3scale-operator-bundle".pathChanged() ||
      "3scale-operator".pathChanged() ||
      "bundle-hack/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: threescale
    appstudio.openshift.io/component: threescale-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: threescale-operator-bundle-on-push
  namespace: 3scale-prod-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/3scale-prod-tenant/threescale-operator-bundle:{{revision}}
  - name: dockerfile
    value: Containerfile.3scale-operator-bundle
  # Do not use hermetic for now as we are going to generate our manifest at build time. We need to pull in content.
  - name: hermetic
    value: "false"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
